server:
  port: 8090
  servlet:
    context-path: /


spring:
  datasource:
    username: crescens
    password: Crescens_1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.165.247:3306/xone?setUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      initial-size: 5
      max-total: 20
      validation-query: select 1
      
      
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30





 